#!/bin/bash
source pipe-tools-utils

THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
ASSETS=${THIS_SCRIPT_DIR}/../assets
ARGS=( \
  DATE_RANGE \
  SOURCE_TABLE \
  SOURCE_FILTER \
  VESSEL_INFO \
  VESSEL_DATABASE \
  SPATIAL_MEASURES \
  COUNTRY_CODES \
  VOYAGES \
  NAMED_ANCHORAGES \
  FISHING_VESSELS \
  MAX_MEDIAN_SPEED_KNOTS \
  TEMP_DATASET
  DEST_TABLE \
)

################################################################################
# Validate and extract arguments
################################################################################
display_usage() {
  ARG_NAMES=$(echo "${ARGS[*]}")
  echo -e "\nUsage:\n$0 $ARG_NAMES\n"
}

if [[ $# -ne ${#ARGS[@]} ]]
then
    display_usage
    exit 1
fi

echo "Running $0"
ARG_VALUES=("$@")
for index in ${!ARGS[*]}; do
  echo "  ${ARGS[$index]}=${ARG_VALUES[$index]}"
  declare "${ARGS[$index]}"="${ARG_VALUES[$index]}"
done

IFS=, read START_DATE END_DATE <<<"${DATE_RANGE}"
if [[ -z $END_DATE ]]; then
  END_DATE=${START_DATE}
fi

end_date_minus_one_day=$(date --date="${END_DATE} -1 day" +%Y-%m-%d)
end_date_minus_two_days=$(date --date="${END_DATE} -2 days" +%Y-%m-%d)

end_date_no_hyphens=${END_DATE//-}
end_date_minus_one_day_no_hyphens=${end_date_minus_one_day//-}
end_date_minus_two_days_no_hyphens=${end_date_minus_two_days//-}

current_table_name="${DEST_TABLE}_v${end_date_no_hyphens}"
one_day_previous_table_name="${DEST_TABLE}_v${end_date_minus_one_day_no_hyphens}"
two_days_previous_table_name="${DEST_TABLE}_v${end_date_minus_two_days_no_hyphens}"

view_name="${DEST_TABLE//:/.}"

echo "Current table=${current_table_name}"
echo "One day previous table=${one_day_previous_table_name}"
echo "Two days previous table=${two_days_previous_table_name}"

################################################################################
# Force that the destination tables exists
################################################################################
echo "Ensuring events table ${current_table_name} exists"
TABLE_DESC=(
  "* Pipeline: ${PIPELINE} ${PIPELINE_VERSION}"
  "* Source: ${SOURCE_TABLE}"
  "* Command:"
  "$(basename $0)"
  "$@"
)
TABLE_DESC=$( IFS=$'\n'; echo "${TABLE_DESC[*]}" )
SCHEMA=${ASSETS}/bigquery/events.schema.json

# Current table
bq mk --force \
  --description "${TABLE_DESC}" \
  --schema ${SCHEMA} \
  --time_partitioning_field=event_start \
  "${current_table_name}"
if [ "$?" -ne 0 ]; then
  echo "  Unable to create table ${current_table_name}"
  exit 1
fi
echo "  Events table exists"


# previous table
echo "Ensuring events table ${one_day_previous_table_name} exists"
bq mk --force \
  --description "${TABLE_DESC}" \
  --schema ${SCHEMA} \
  --time_partitioning_field=event_start \
  "${one_day_previous_table_name}"
if [ "$?" -ne 0 ]; then
  echo "  Unable to create table ${one_day_previous_table_name}"
  exit 1
fi
echo "  Events table exists"

################################################################################
# Delete existing records
################################################################################
DELETE_SQL=${ASSETS}/bigquery/delete-daterange.sql.j2
echo "Deleting existing records for ${START_DATE} to ${END_DATE}"
jinja2 ${DELETE_SQL} \
  -D table=${current_table_name//:/.} \
  -D start_date=${START_DATE} \
  -D end_date=${END_DATE} \
  | bq query --max_rows=0
if [ "$?" -ne 0 ]; then
  echo "  Unable to delete records for table ${current_table_name} from ${START_DATE} to ${END_DATE}"
  exit 1
fi

################################################################################
# First generate intermediate encounter results into a temp table
################################################################################
echo "Generating intermediate results table"
UUID=$(uuidgen)
INTERMEDIATE_TABLE="${TEMP_DATASET}.${UUID//-/_}"
SQL=${ASSETS}/bigquery/events-encounter-events-01.sql.j2
jinja2 ${SQL} \
  -D source_table=${SOURCE_TABLE//:/.} \
  -D source_filter=${SOURCE_FILTER} \
  -D vessel_info=${VESSEL_INFO//:/.} \
  -D vessel_database=${VESSEL_DATABASE//:/.} \
  -D spatial_measures=${SPATIAL_MEASURES//:/.} \
  -D country_codes=${COUNTRY_CODES//:/.} \
  -D voyages=${VOYAGES//:/.} \
  -D named_anchorages=${NAMED_ANCHORAGES//:/.} \
  -D fishing_vessels=${FISHING_VESSELS//:/.} \
  -D max_median_speed_knots=${MAX_MEDIAN_SPEED_KNOTS} \
  | bq query --max_rows=0 --allow_large_results --replace --destination_table ${INTERMEDIATE_TABLE}

if [ "$?" -ne 0 ]; then
  echo "  Unable to insert records for table ${INTERMEDIATE_TABLE}"
  exit 1
fi

################################################################################
# Run the actual results query which converts the intermediate results into
# real data
################################################################################
echo "Processing intermediate results"
SQL=${ASSETS}/bigquery/events-encounter-events-02.sql.j2
jinja2 ${SQL} \
  -D complete_encounter_with_authorizations=${INTERMEDIATE_TABLE} \
  | bq query \
    --max_rows=0 \
    --allow_large_results \
    --append_table \
    --destination_table ${current_table_name}

if [ "$?" -ne 0 ]; then
  echo "  Unable to insert records for table ${current_table_name}"
  exit 1
fi

################################################################################
# Remove the intermediate results table
################################################################################
echo "Deleting intermediate results table"
bq rm -t -f ${INTERMEDIATE_TABLE}

if [ "$?" -ne 0 ]; then
  echo "  Unable to remove intermediate table ${INTERMEDIATE_TABLE}"
  exit 1
fi

################################################################################
# Create new view
################################################################################
echo "Creating view [${view_name}]"
echo "CREATE OR REPLACE VIEW ${view_name} OPTIONS(description=\"published_events_encounters\") AS SELECT * FROM ${current_table_name//:/.}"

bq query \
  --use_legacy_sql=false \
  "CREATE OR REPLACE VIEW ${view_name} OPTIONS(description=\"published_events_encounters\") AS SELECT * FROM ${current_table_name//:/.}"
if [ "$?" -ne 0 ]; then
  echo "  Unable to create view ${view_name}"
  exit 1
fi

################################################################################
# Remove two days before table
################################################################################
echo "Removing two days before table [${two_days_previous_table_name}]"
bq rm -f -t "${two_days_previous_table_name}"
if [ "$?" -ne 0 ]; then
  echo "  Unable to remove temporal table ${two_days_previous_table_name}"
  exit 1
fi

echo "${current_table_name} Done."
