#!/bin/bash
source pipe-tools-utils

THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
# source ${THIS_SCRIPT_DIR}/pipeline.sh
ASSETS=${THIS_SCRIPT_DIR}/../assets
ARGS=( \
  SOURCE_RAW_LOITERING_EVENTS \
  SOURCE_SEGMENT_INFO \
  SOURCE_SPATIAL_MEASURES \
  SOURCE_COUNTRY_CODES \
  SOURCE_VOYAGES \
  SOURCE_NAMED_ANCHORAGES \
  SOURCE_SEGS \
  DEST_TABLE \
)

################################################################################
# Validate and extract arguments
################################################################################
display_usage() {
  echo -e "\nUsage:\n$0 SOURCE_RAW_LOITERING_EVENTS SOURCE_SEGMENT_INFO SOURCE_SPATIAL_MEASURES SOURCE_COUNTRY_CODES SOURCE_VOYAGES SOURCE_NAMED_ANCHORAGES SOURCE_SEGS DEST_TABLE"
}

if [[ $# -ne ${#ARGS[@]} ]]
then
    display_usage
    exit 1
fi

ARG_VALUES=("$@")
PARAMS=()
for index in ${!ARGS[*]}; do
  echo "${ARGS[$index]}=${ARG_VALUES[$index]}"
  declare "${ARGS[$index]}"="${ARG_VALUES[$index]}"
done

echo "Running $0"
echo "  SOURCE_RAW_LOITERING_EVENTS: $SOURCE_RAW_LOITERING_EVENTS"
echo "  SOURCE_SEGMENT_INFO: $SOURCE_SEGMENT_INFO"
echo "  SOURCE_SPATIAL_MEASURES: $SOURCE_SPATIAL_MEASURES"
echo "  SOURCE_COUNTRY_CODES: $SOURCE_COUNTRY_CODES"
echo "  SOURCE_VOYAGES: $SOURCE_VOYAGES"
echo "  SOURCE_NAMED_ANCHORAGES: $SOURCE_NAMED_ANCHORAGES"
echo "  SOURCE_SEGS: $SOURCE_SEGS"
echo "  DEST_TABLE: $DEST_TABLE"
################################################################################
# Force that the destination table exists
################################################################################
echo "Ensuring events table ${DEST_TABLE} exists"
TABLE_DESC=(
  "* Pipeline: ${PIPELINE} ${PIPELINE_VERSION}"
  "* Source: ${SOURCE_TABLE}"
  "* Command:"
  "$(basename $0)"
  "$@"
)
TABLE_DESC=$( IFS=$'\n'; echo "${TABLE_DESC[*]}" )
SCHEMA=${ASSETS}/bigquery/events.schema.json
bq mk --force \
  --description "${TABLE_DESC}" \
  ${DEST_TABLE}

if [ "$?" -ne 0 ]; then
  echo "  Unable to create table ${DEST_TABLE}"
  exit 1
fi
echo "  Events table exists"

################################################################################
# Generate the loitering events
################################################################################
echo "Generating loitering events at ${DEST_TABLE}"
SQL=${ASSETS}/bigquery/carrier-loitering-events.sql.j2
jinja2 ${SQL} \
  -D raw_loitering_events=${SOURCE_RAW_LOITERING_EVENTS//:/.} \
  -D segment_info=${SOURCE_SEGMENT_INFO//:/.} \
  -D spatial_measures=${SOURCE_SPATIAL_MEASURES//:/.} \
  -D country_codes=${SOURCE_COUNTRY_CODES//:/.} \
  -D voyages=${SOURCE_VOYAGES//:/.} \
  -D named_anchorages=${SOURCE_NAMED_ANCHORAGES//:/.} \
  -D segs=${SOURCE_SEGS//:/.} \
  | bq query --max_rows=0 --allow_large_results --replace --destination_table ${DEST_TABLE}

if [ "$?" -ne 0 ]; then
  echo "  Unable to insert records for table ${DEST_TABLE}"
  exit 1
fi

echo "${DEST_TABLE} Done."
