#!/bin/bash
source pipe-tools-utils

THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
# source ${THIS_SCRIPT_DIR}/pipeline.sh
ASSETS=${THIS_SCRIPT_DIR}/../assets
ARGS=( \
  DATE_RANGE \
  PUBLISHED_EVENTS_PORT_VISITS \
  PUBLISHED_EVENTS_ENCOUNTERS \
  PUBLISHED_EVENTS_LOITERING \
  VESSEL_INFO \
  CONFIDENCE \
  MIN_EVENT_HOURS \
  DEST_TABLE \
)

################################################################################
# Validate and extract arguments
################################################################################
display_usage() {
  ARG_NAMES=$(echo "${ARGS[*]}")
  echo -e "\nUsage:\n$0 $ARG_NAMES\n"
}

if [[ $# -ne ${#ARGS[@]} ]]
then
    display_usage
    exit 1
fi

echo "Running $0"
ARG_VALUES=("$@")
for index in ${!ARGS[*]}; do
  echo "  ${ARGS[$index]}=${ARG_VALUES[$index]}"
  declare "${ARGS[$index]}"="${ARG_VALUES[$index]}"
done

IFS=, read START_DATE END_DATE <<<"${DATE_RANGE}"
if [ -z $END_DATE ] || [ $END_DATE == $START_DATE ]; then
  END_DATE=$(date +%Y-%m-%d -d "$START_DATE + 1 day")
fi
################################################################################
# Force that the destination table exists
################################################################################
echo "Ensuring events table ${DEST_TABLE} exists"
TABLE_DESC=(
  "* Pipeline: ${PIPELINE} ${PIPELINE_VERSION}"
  "* Source: ${SOURCE_TABLE}"
  "* Command:"
  "$(basename $0)"
  "$@"
)
TABLE_DESC=$( IFS=$'\n'; echo "${TABLE_DESC[*]}" )
SCHEMA=${ASSETS}/bigquery/events.schema.json
bq mk --force \
  --description "${TABLE_DESC}" \
  ${DEST_TABLE} \
  ${SCHEMA}

if [ "$?" -ne 0 ]; then
  echo "  Unable to create table ${DEST_TABLE}"
  exit 1
fi
echo "  Events table exists"

################################################################################
# Generate the anchorage events
################################################################################
echo "Generating port events at ${DEST_TABLE}"
SQL=${ASSETS}/bigquery/events-anchorage-events.sql.j2
jinja2 ${SQL} \
  -D start_date=${START_DATE} \
  -D end_date=${END_DATE} \
  -D published_events_port_visits=${PUBLISHED_EVENTS_PORT_VISITS//:/.} \
  -D published_events_encounters=${PUBLISHED_EVENTS_ENCOUNTERS//:/.} \
  -D published_events_loitering=${PUBLISHED_EVENTS_LOITERING//:/.} \
  -D vessel_info=${VESSEL_INFO//:/.} \
  -D confidence=${CONFIDENCE//:/.} \
  -D min_event_hours=${MIN_EVENT_HOURS//:/.} \
  | bq query --max_rows=0 --allow_large_results --replace --destination_table ${DEST_TABLE}

if [ "$?" -ne 0 ]; then
  echo "  Unable to insert records for table ${DEST_TABLE}"
  exit 1
fi

echo "${DEST_TABLE} Done."
