#!/usr/bin/env bash

THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"

display_usage() {
	echo "Available Commands"
	echo "  generate_carrier_encounter_events  publish carrier-specific encounter (vessel rendevouz at sea between a carrier and a fishing vessel) events"
	echo "  generate_carrier_loitering_events  publish carrier-specific loitering (carrier vessel drifting at sea) events"
	echo "  generate_carrier_anchorage_events  publish carrier-specific anchorage (carrier docking at anchorage) events"
	echo "  publish_vessel_tracks              publish tracks of vessels related to the carrier portal to postgres"
	echo "  publish_vessel_info                export the vessel information related to carrier portal vessels to elastic search"
  echo "  publish_events                     publish events of a given bigquery table to a postgres database"
	}


if [[ $# -le 0 ]]
then
    display_usage
    exit 1
fi


case $1 in

  generate_carrier_encounter_events)
    ${THIS_SCRIPT_DIR}/generate_carrier_encounter_events "${@:2}"
    ;;

  generate_carrier_loitering_events)
    ${THIS_SCRIPT_DIR}/generate_carrier_loitering_events "${@:2}"
    ;;

  generate_carrier_anchorage_events)
    ${THIS_SCRIPT_DIR}/generate_carrier_anchorage_events "${@:2}"
    ;;

  publish_vessel_tracks)
    ${THIS_SCRIPT_DIR}/publish_vessel_tracks "${@:2}"
    ;;

  publish_vessel_info)
    ${THIS_SCRIPT_DIR}/publish_vessel_info "${@:2}"
    ;;

  publish_events)
    ${THIS_SCRIPT_DIR}/publish_events "${@:2}"
    ;;

  *)
    display_usage
    exit 1
    ;;
esac
