#!/usr/bin/env bash

THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"

display_usage() {
	echo "Available Commands"
	echo "  generate_carrier_encounter_events  publish carrier-specific encounter (vessel rendevouz at sea between a carrier and a fishing vessel) events"
	echo "  generate_carrier_loitering_events  publish carrier-specific loitering (carrier vessel drifting at sea) events"
  echo "  publish_postgres                   publish events of a given bigquery table to a postgres database"
	}


if [[ $# -le 0 ]]
then
    display_usage
    exit 1
fi


case $1 in

  generate_carrier_encounter_events)
    ${THIS_SCRIPT_DIR}/generate_carrier_encounter_events "${@:2}"
    ;;

  generate_carrier_loitering_events)
    ${THIS_SCRIPT_DIR}/generate_carrier_loitering_events "${@:2}"
    ;;

  publish_postgres)
    ${THIS_SCRIPT_DIR}/publish_postgres "${@:2}"
    ;;

  *)
    display_usage
    exit 1
    ;;
esac
